modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="interaction"
version="0.0.1"
displayName="Interaction"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Made using MCreator, Blockbench, & Paint 3D"
authors="10neGamer1"
description="A mod aiming to make your worlds more immersive with Interactions!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.interaction]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.interaction]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration